"""学术写作质量检查：文体、引用分布、来源清单与时效覆盖。

与 ``gates.py`` 的结构类检查互补，这里关注「科研交付物读起来是否可信」：

* ``register``  —— 口语化措辞、成对套话、中文夹半角标点、生产过程叙述、超长句；
* ``abstract``  —— 摘要 / 一句话总结不得带引用角标；
* ``cluster``   —— 单处并列引用过多（引用堆砌）；
* ``sources``   —— 重复来源（同一文献以不同 URL 重复计数）、引用下限；
* ``recency``   —— 任务点名年份时，已核验来源里必须真有该年份及之后的文献；
* ``limitations`` —— 需要说明局限的任务必须有局限 / 不确定性段落。

每项检查都返回可直接交给写作者返工的**具体问题**（带原句摘录），而不是一个分数。
检查全部确定性、只读正文与运行数据，不调用模型。
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Literal

from .delivery.markdown import parse_blocks, plain
from .delivery.math_markdown import citation_text
from .quality import QualityPolicy

Severity = Literal["error", "warning"]


@dataclass(frozen=True)
class Finding:
    code: str
    severity: Severity
    message: str
    excerpt: str = ""

    def render(self) -> str:
        return f"{self.message}" + (f"：「{self.excerpt}」" if self.excerpt else "")


@dataclass
class ScholarlyReport:
    findings: list[Finding] = field(default_factory=list)
    metrics: dict[str, int] = field(default_factory=dict)

    @property
    def errors(self) -> list[Finding]:
        return [f for f in self.findings if f.severity == "error"]

    @property
    def warnings(self) -> list[Finding]:
        return [f for f in self.findings if f.severity == "warning"]


_CITE = re.compile(r"\[(\d+(?:\s*[,，]\s*\d+)*)\]")
_REFERENCES_SPLIT = re.compile(r"\n#{1,3}\s*(?:参考来源|参考文献|References)\s*\n")

# 成对套话：同一句内出现前后两半才算命中（跨句不算）。
_PAIRED_FRAMES: tuple[tuple[str, str, str], ...] = (
    ("不是", "而是", "不是……而是……"),
    ("不在于", "而在于", "不在于……而在于……"),
    ("与其", "不如", "与其……不如……"),
    ("不仅", "而且", "不仅……而且……"),
    ("既", "又", "既……又……"),
    ("一方面", "另一方面", "一方面……另一方面……"),
    ("看似", "实则", "看似……实则……"),
)
# 「既」「又」单字过于常见（既有、又称），只在明显的并列结构里判：既 + 2–12 字 + 又
_JI_YOU = re.compile(r"既[^，。；,;]{1,12}又")

_COLLOQUIAL = (
    "简单来说",
    "说白了",
    "其实",
    "总的来说",
    "众所周知",
    "毋庸置疑",
    "不得不说",
    "非常非常",
    "超级",
    "巨大的突破",
    "颠覆性",
    "革命性",
    "值得一提的是",
    "让我们",
    "我们可以看到",
    "In recent years",
    "It is well known",
    "cutting-edge",
    "game-changer",
)

_PRODUCTION = re.compile(
    r"(?:作为(?:一个)?\s*(?:AI|人工智能|语言模型)|由\s*(?:AI|ChatGPT|大模型)\s*生成|"
    r"用户上传|用户提供的附件|根据您提供|本系统|检索结果显示|素材未覆盖以外|"
    r"generated by (?:AI|ChatGPT)|as an AI|uploaded (?:file|attachment))",
    re.I,
)

# 中文语境下的半角标点：前后都是汉字的半角逗号 / 分号 / 冒号 / 问号 / 叹号
_CJK_ASCII_PUNCT = re.compile(r"(?<=[一-鿿])[,;:?!](?=[一-鿿])")

_YEAR_REQUEST = re.compile(
    r"((?:19|20)\d{2})\s*(?:年)?\s*(?:以来|之后|以后|至今|及以后|起|后|onwards|since|after|-|–|—)"
)
_YEAR_ANY = re.compile(r"(?<!\d)((?:19|20)\d{2})(?!\d)")
_SINCE_EN = re.compile(r"(?:since|after|from)\s+((?:19|20)\d{2})", re.I)

_ABSTRACT_TITLES = ("摘要", "一句话总结", "abstract", "tl;dr", "summary", "执行摘要", "概述")
_LIMITATION_WORDS = (
    "局限",
    "不足",
    "限制",
    "不确定",
    "未解",
    "开放问题",
    "未来方向",
    "挑战",
    "limitation",
    "open problem",
    "uncertain",
)


def _body(markdown: str) -> str:
    return _REFERENCES_SPLIT.split(markdown, maxsplit=1)[0]


def _sentences(text: str) -> list[str]:
    parts = re.split(r"(?<=[。！？!?；;])\s*|\n+", text)
    return [p.strip() for p in parts if p.strip()]


def _prose_lines(markdown: str) -> list[str]:
    """正文段落与列表项的纯文本（去掉标题、代码、表格、公式与图片）。"""
    lines: list[str] = []

    def add(inlines: list) -> None:  # type: ignore[type-arg]
        text = plain([inline for inline in inlines if not inline.math and not inline.code])
        if text.strip():
            lines.append(text.strip())

    for block in parse_blocks(_body(markdown)):
        if block.kind in {"paragraph", "quote"}:
            add(block.inlines)
        elif block.kind == "list":
            for item in block.items:
                add(item.inlines)
    return lines


def _short(text: str, limit: int = 40) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= limit else text[:limit] + "…"


def check_register(markdown: str, policy: QualityPolicy) -> list[Finding]:
    findings: list[Finding] = []
    prose = _prose_lines(markdown)
    for line in prose:
        for sentence in _sentences(line):
            for first, second, label in _PAIRED_FRAMES:
                if first == "既":
                    if _JI_YOU.search(sentence):
                        findings.append(
                            Finding(
                                "paired-frame", "error", f"成对套话「{label}」", _short(sentence)
                            )
                        )
                    continue
                head = sentence.find(first)
                if head >= 0 and sentence.find(second, head + len(first)) > head:
                    findings.append(
                        Finding("paired-frame", "error", f"成对套话「{label}」", _short(sentence))
                    )
                    break
            if len(re.sub(r"\s", "", sentence)) > policy.max_sentence_chars:
                findings.append(
                    Finding(
                        "overlong-sentence",
                        "warning",
                        f"超长句（超过 {policy.max_sentence_chars} 字），建议拆分",
                        _short(sentence),
                    )
                )
        lowered = line.casefold()
        for phrase in _COLLOQUIAL:
            if phrase.casefold() in lowered:
                findings.append(
                    Finding("colloquial", "error", f"口语化或夸张措辞「{phrase}」", _short(line))
                )
        match = _PRODUCTION.search(line)
        if match:
            findings.append(
                Finding(
                    "production-narration",
                    "error",
                    f"正文出现生产过程描述「{match.group(0)}」",
                    _short(line),
                )
            )
        punct = _CJK_ASCII_PUNCT.search(line)
        if punct:
            findings.append(
                Finding(
                    "cjk-ascii-punctuation",
                    "warning",
                    f"中文句中使用了半角标点「{punct.group(0)}」",
                    _short(line),
                )
            )
    # 同一问题在长文里可能命中很多次：按 (code, message) 去重，最多保留 12 条
    unique: dict[tuple[str, str], Finding] = {}
    for item in findings:
        unique.setdefault((item.code, item.message), item)
    return list(unique.values())[:12]


def _sections(markdown: str) -> list[tuple[str, str]]:
    """(二级标题, 该节正文) 列表。"""
    parts = re.split(r"(?m)^##\s+(.+?)\s*$", _body(markdown))
    return [(parts[i].strip(), parts[i + 1]) for i in range(1, len(parts) - 1, 2)]


def check_abstract(markdown: str) -> list[Finding]:
    for title, text in _sections(markdown):
        if any(key in title.casefold() for key in _ABSTRACT_TITLES):
            if _CITE.search(citation_text(text)):
                return [
                    Finding(
                        "abstract-citation",
                        "error",
                        f"「{title}」中出现引用角标；摘要应能脱离正文独立阅读，来源归属放到正文",
                    )
                ]
    return []


def check_clusters(markdown: str, policy: QualityPolicy) -> list[Finding]:
    worst = 0
    example = ""
    for match in _CITE.finditer(citation_text(_body(markdown))):
        size = len(re.split(r"\s*[,，]\s*", match.group(1)))
        if size > worst:
            worst, example = size, match.group(0)
    if worst > policy.max_citation_cluster:
        return [
            Finding(
                "citation-cluster",
                "error",
                f"单处并列 {worst} 个引用（上限 {policy.max_citation_cluster}），"
                "请拆分论断并说明每个来源各自支撑什么",
                example,
            )
        ]
    return []


def _normalize_url(url: str) -> str:
    from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

    from ..tools.composite import normalize_url

    url = normalize_url(url)
    parts = urlsplit(url)
    if parts.hostname == "workspace.invalid" and parts.path.startswith(
        ("/attachments/", "/pasted/")
    ):
        # Chunks in the same uploaded paper share a document identity. Other
        # URLs keep document-selecting queries such as article?id=123.
        query = urlencode([(key, value) for key, value in parse_qsl(parts.query) if key != "chunk"])
        url = urlunsplit((parts.scheme, parts.netloc, parts.path, query, ""))
    elif any(
        key == "dr_section" and re.fullmatch(r"pdf-\d+", value)
        for key, value in parse_qsl(parts.query)
    ):
        query = urlencode(
            [
                (key, value)
                for key, value in parse_qsl(parts.query)
                if not (key == "dr_section" and re.fullmatch(r"pdf-\d+", value))
            ]
        )
        url = urlunsplit((parts.scheme, parts.netloc, parts.path, query, ""))
    url = re.sub(r"^https?://(www\.)?", "", url.strip(), flags=re.I).rstrip("/")
    url = re.sub(r"arxiv\.org/(?:abs|pdf)/(\d{4}\.\d{4,5})(?:v\d+)?(?:\.pdf)?", r"arxiv:\1", url)
    return url


def source_counts(
    citations: list[str], references: dict[str, str] | None = None
) -> tuple[int, list[str]]:
    from urllib.parse import parse_qs, urlsplit

    def chunk_family(url: str) -> str | None:
        parts = urlsplit(url)
        if (
            parts.hostname == "workspace.invalid"
            and parts.path.startswith(("/attachments/", "/pasted/"))
            and "chunk" in parse_qs(parts.query)
        ):
            return _normalize_url(url)
        if re.fullmatch(r"chunk-\d+", parts.fragment.rsplit("#", 1)[-1]) or any(
            re.fullmatch(r"pdf-\d+", value) for value in parse_qs(parts.query).get("dr_section", [])
        ):
            return _normalize_url(url)
        return None

    seen: dict[str, str] = {}
    duplicates: list[str] = []
    repeated = 0
    for url in citations:
        key = _normalize_url(url)
        reference = (references or {}).get(url, "")
        title_key = re.sub(r"\W+", "", reference.casefold())[:80] if reference else ""
        for candidate in filter(None, (key, title_key)):
            if candidate in seen:
                repeated += 1
                # Multiple quote locations in one uploaded document are valid
                # anchors. Count one document without asking the writer to erase them.
                family = chunk_family(url)
                if (
                    seen[candidate] == url
                    or family is None
                    or family != chunk_family(seen[candidate])
                ):
                    duplicates.append(url)
                break
            seen[candidate] = url
    return max(0, len(citations) - repeated), duplicates


def check_sources(
    citations: list[str], used: int, minimum: int, *, references: dict[str, str] | None = None
) -> list[Finding]:
    findings: list[Finding] = []
    unique, duplicates = source_counts(citations, references)
    if duplicates:
        findings.append(
            Finding(
                "duplicate-source",
                "error",
                f"{len(duplicates)} 个来源与其它来源是同一文献（不同链接），重复计数",
                _short(duplicates[0], 60),
            )
        )
    distinct = max(0, used - (len(citations) - unique))
    if minimum and distinct < minimum:
        findings.append(
            Finding(
                "citation-shortfall",
                "error",
                f"正文实际引用 {distinct} 个不同的已核验来源，少于下限 {minimum} 个",
            )
        )
    return findings


def requested_year(query: str) -> int | None:
    """任务文本里点名的起始年份（「2025 年以来」「since 2024」「2024–2026」）。"""
    for pattern in (_YEAR_REQUEST, _SINCE_EN):
        match = pattern.search(query)
        if match:
            return int(match.group(1))
    return None


def check_recency(query: str, source_texts: list[str]) -> list[Finding]:
    year = requested_year(query)
    if year is None:
        return []
    hits = sum(1 for text in source_texts if any(int(y) >= year for y in _YEAR_ANY.findall(text)))
    if hits == 0:
        return [
            Finding(
                "recency-gap",
                "error",
                f"任务要求 {year} 年及之后的文献，但已核验来源中找不到该时段的文献",
            )
        ]
    return []


def check_limitations(markdown: str) -> list[Finding]:
    body = _body(markdown).casefold()
    if any(word in body for word in _LIMITATION_WORDS):
        return []
    return [
        Finding(
            "missing-limitations",
            "error",
            "没有说明局限、不确定性或未解决的问题；科研交付物必须写明结论的边界",
        )
    ]


def uncited_sections_for(scratch: dict[str, object]) -> tuple[str, ...]:
    """从黑板上的任务契约推出不带引用的章节（无契约的普通研究为空）。"""
    from .contract import contract_from_scratch
    from .quality import coerce_policy

    contract = contract_from_scratch(scratch)  # type: ignore[arg-type]
    if contract is None:
        return ()
    return abstract_sections(contract.template, coerce_policy(contract.quality))


def abstract_sections(template_key: str, policy: QualityPolicy) -> tuple[str, ...]:
    """按规范不带引用角标的章节标题关键词（交给引用复核豁免「必须引用」）。"""
    if policy.forbid_abstract_citations and template_key in _ABSTRACT_TEMPLATES:
        return _ABSTRACT_TITLES
    return ()


_LIMITATION_TEMPLATES = {"litReview", "autoResearch", "paperRead", "peerReview"}
_ABSTRACT_TEMPLATES = {"litReview", "autoResearch", "paperRead"}
_REGISTER_TEMPLATES = {"litReview", "autoResearch", "paperRead", "peerReview", "dataAnalysis"}


def evaluate(
    markdown: str,
    *,
    template_key: str,
    query: str,
    citations: list[str],
    used_citations: int,
    min_citations: int,
    policy: QualityPolicy,
    source_texts: list[str] | None = None,
    references: dict[str, str] | None = None,
) -> ScholarlyReport:
    """对一篇定稿跑全部学术检查；按任务类型与策略开关决定跑哪些。"""
    report = ScholarlyReport()
    if policy.register_check and template_key in _REGISTER_TEMPLATES:
        report.findings += check_register(markdown, policy)
    if policy.forbid_abstract_citations and template_key in _ABSTRACT_TEMPLATES:
        report.findings += check_abstract(markdown)
    if citations:
        report.findings += check_clusters(markdown, policy)
    report.findings += check_sources(
        citations, used_citations, min_citations, references=references
    )
    if policy.recency_check and source_texts is not None:
        report.findings += check_recency(query, source_texts)
    if policy.require_limitations and template_key in _LIMITATION_TEMPLATES:
        report.findings += check_limitations(markdown)
    report.metrics = {
        "errors": len(report.errors),
        "warnings": len(report.warnings),
        "citations_used": source_counts(citations, references)[0],
        "citation_anchors_used": used_citations,
        "citations_required": min_citations,
    }
    return report


def revision_brief(report: ScholarlyReport, extra: list[str] | None = None) -> str:
    """把检查结果写成交给写作者的返工说明。"""
    items = [f"- {finding.render()}" for finding in report.errors]
    items += [f"- （建议）{finding.render()}" for finding in report.warnings[:5]]
    items += [f"- {line}" for line in extra or []]
    return (
        "上一版未通过交付质量检查，请在保持全部引用角标与数值忠实于素材的前提下修订全文，"
        "逐条解决以下问题；素材确实无法支持的内容，删除或明确标注「素材未覆盖」，"
        "不得为凑数引入素材外的文献或事实：\n" + "\n".join(items)
    )


__all__ = [
    "Finding",
    "ScholarlyReport",
    "abstract_sections",
    "check_abstract",
    "check_clusters",
    "check_limitations",
    "check_recency",
    "check_register",
    "check_sources",
    "evaluate",
    "requested_year",
    "revision_brief",
]
